name: 뱀 만들기

on:
  schedule:
    - cron: '0 0 * * *'   # 매일 자동으로
  workflow_dispatch:       # 버튼 누르면 바로

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 뱀 그림 그리기
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Selene-ovo
          outputs: |
            snake.svg

      - name: 저장하기
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
